language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install: tests/install_dependencies.sh

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit tests/